spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
#      ddl-auto: update #always use none in prod env, never use create-drop
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

server:
  port: 9092
